#!/bin/sh
# AppImage entry point: make the bundled ORX library findable, then run.
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"
exec "$HERE/usr/bin/rockrun" "$@"
